apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pet-matcher
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
    spec:
      serviceAccountName: pet-matcher-runtime@petspotr.iam.gserviceaccount.com
      timeoutSeconds: 600
      containers:
        - image: gcr.io/petspotr/pet-matcher:latest
          env:
            - name: PETSPOTR_IMAGE_BUCKET
              value: petspotr-pet-images
            - name: PUBSUB_PUSH_SUBSCRIPTION
              value: projects/petspotr/subscriptions/found-pet-matcher
            - name: PUBSUB_LOST_SUBSCRIPTION
              value: projects/petspotr/subscriptions/lost-pet-matcher-analysis
            - name: PUBSUB_PUSH_SERVICE_ACCOUNT
              value: pubsub-pet-matcher-invoker@petspotr.iam.gserviceaccount.com
          resources:
            limits:
              cpu: 2000m
              memory: 2Gi
